version: "3.9"

services:
  app:
    build: .
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mongo:latest
#    env_file:
#      - .env
    ports:
      - "27017:27017"
    environment:
#      - MONGO_INITDB_DATABASE:${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=root_user
      - MONGO_INITDB_ROOT_PASSWORD=password123

    volumes:
      - mongodb:/data/db

volumes:
  mongodb: